Repository storybookjs/vite-plugin-storybook-nextjs, pull requests merged in 2024-08, with the labels that each got.

#8 Fix aliases
  package.json
  src/index.ts
  src/mocks/storybook.global.ts
  src/plugins/next-image/plugin.ts
  src/plugins/next-mocks/plugin.ts
  src/plugins/next-swc/plugin.ts
  src/utils.ts
  src/utils/nextjs.ts
  tsup.config.ts
Labels: patch

#9 Add docs
  CONTRIBUTING.md
  LICENSE.md
  README.md
  TODO.md
  package.json
Labels: major

#12 Prose tweaks and other improvements for README
  README.md
Labels: documentation, patch

#11 Update Readme.md related to addon-vitest
  README.md
Labels: documentation, skip-release

#14 Widen Next.js version requirement
  README.md
  package.json
Labels: patch

#15 fix: Do not fail if pages/apps dir cannot be found
  src/plugins/next-swc/plugin.ts
  src/utils/nextjs.test.ts
  src/utils/nextjs.ts
Labels: patch

#16 fix: Type declaration exports
  package.json
Labels: patch
