Repository storybookjs/vite-plugin-storybook-nextjs, pull requests merged in 2025-06, with the labels that each got.

#41 Use tsconfig paths plugin
  package.json
  pnpm-lock.yaml
  src/index.ts
Labels: enhancement, patch

#45 Next.js: Support v15.4
  example/package.json
  package.json
  pnpm-lock.yaml
  src/index.ts
  src/plugins/next-env/plugin.ts
Labels: bug, patch

#44 Fix JSON.parse error in vitePluginNextFont
  src/plugins/next-font/plugin.ts
Labels: patch
